### ISSUE TITLE
Add public/private setting

### ISSUE THREAD

**Issue by beryllium** [snipe/lessthanthrees#11]
Users may not want 100% of their items to be public.

(At the moment it seems that 100% of the items are private? :) )

**Comment by snipe** [comment]
100% are public right now.

**Comment by snipe** [comment]
https://snipe.lessthanthrees.com/movies
https://snipe.lessthanthrees.com/games
etc

**Comment by beryllium** [comment]
Ah! That's a bit unclear when landing directly on the Public Profile link (e.g., https://snipe.lessthanthrees.com )
