### ISSUE TITLE
Delete option does not appear to work

### ISSUE THREAD

**Issue by beryllium** [snipe/lessthanthrees#12]
The "X" to delete items doesn't seem to be wired up. I'd suggest a confirmation & a bulk delete/modify option (checkboxes with buttons to delete or make public/make private at the bottom).

**Comment by snipe** [comment]
They do work. I'll be making the UI more clear, but they do work as far as I know. Can only delete from your https://lessthanthrees.com/home screen tho

**Comment by beryllium** [comment]
It appears to be a CSS issue. In Chrome 56, the X button only activates when the mouse cursor is over the top 1/5th of the "X" (or slightly above the X).

This is on a list with only 1 item, BTW.

**Comment by snipe** [comment]
Chrome on what OS? (I'm using Chrome on Mac OS)

**Comment by beryllium** [comment]
MacOS also. I can make a quicktime video of the issue if that would help.

**Comment by snipe** [comment]
I don't think that will help. I understand the bug report, but am unable to reproduce it here. :-/

**Comment by beryllium** [comment]
Ooh, strange. If I right-click the X when it's grey, and choose "Inspect", it actually selects the preceding `<div class="footer">` that holds the item counter. If I do the same when the highlight colour is activated, it properly selects the `<a>`. I wonder if it's a z-index issue?

It seems to be influenced by the `position:absolute` on the footer class.

**Comment by beryllium** [comment]
Very nice! I like the circle. Thanks! 👍
